name: Covid Scraping 
on: 
  schedule:
        - cron: "*/5 * * * *" #runs at every 5 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute scrape.py 
        run: python scrape.py

      - name: execute dbmodule.py
        run: python dbmodule.py


          